Add test-cmd optional to execute custom test command in go-ci
parsleyhealth/github-composite-actions pull request #15
Opened 2022-11-07 16:43 UTC by duchoparsley

Hi @chiefy,

I would like to add a new option to allow the go-ci to execute a custom test command. Some repos need to run integration tests by executing a custom command. Could you please help me review it?

Thanks & Best Regards

2022-11-07 16:48 UTC, chiefy requested changes
can you just bump this to 4.3 since it's not a bugfix, thanks

2022-11-07 16:52 UTC, duchoparsley commented
Hi @chiefy, I've bumped it. Please approve! Thanks

2022-11-08 18:09 UTC, chiefy approved these changes

2022-11-09 17:04 UTC, merged

2023-02-04 16:29 UTC, ChiefGhostZero0x1 reviewed
The first thing that comes to mind is that I have no idea how much of this stuff I need to do for the next couple of months because I'm going through all this stuff right now and I'm just trying to figure it out because I'm really struggling with my anxiety and I don't know what I'm going to do with myself right away because of all this stress and I don't want to be in the situation where I'm not in a place that I'm self sufficient.